#!/bin/zsh -f

# Clone github-style repositories into directories named by user and repo

for REPOSITORY in $@ ; do
   REPO_COMPONENTS=(${(@s:/:)${REPOSITORY:r}})
   if [[ ${PWD:t} == $REPO_COMPONENTS[-2] ]] ; then
      DESTINATION_DIR=${REPO_COMPONENTS[-1]}
   else
      DESTINATION_DIR=${(j:/:)REPO_COMPONENTS[-2,-1]}
   fi
   git clone $REPOSITORY $DESTINATION_DIR
done
